spring:
  application:
    name: gateway
  # 加上这个配置 否则zuul启动会有警告信息 查看启动日志
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 8085
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
#    healthcheck:
#      enabled: true
#    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
# zuul.routes.*.path  拦截请求的路径，其中*表示分组标记，用于路由配置
# zuul.routes.*.service-id  根据分组标记将拦截的请求转发到服务提供方
zuul:
  # Zuul 会把代理的前缀给移除掉，如果不想被移除掉，可以使用 stripPrefix=false 来取消
  prefix: /api
  routes:
    house:
      path: /house/**
      service-id: service-provider
      stripPrefix: false
    substitution:
      path: /substitution/**
      service-id: service-consumer
      stripPrefix: false
#management:
#  #actuator端口
#  server:
#    port: 9001
#  #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
#  endpoints:
#    web:
#      base-path: /actuator
#      #开放所有页面节点  默认只开启了health、info两个节点
#      exposure:
#        include: "*"
#    #显示健康具体信息  默认不会显示详细信息
#  endpoint:
#    health:
#      show-details: always
logging:
  level:
    root: info
# 参考https://blog.csdn.net/weixin_41758046/article/details/88902073
# 禁用ribbon缓存，每次查找都从注册中心找
#ribbon:
#  eureka:
#    enabled: false
# zuul实现了熔断处理
#hystrix:
#  metrics:
#    enabled: false